"""Regenerate U_NET_Segmentation.ipynb for Colab (2048 tiles, 1024 crops)."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION = "1.11.0"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# U-Net + MobileNetV2 — v{VERSION} (crop 1024 from 2048)\n",
            "\n",
            f"**Notebook version:** `{VERSION}` — bump this string on every GitHub push.\n",
            "\n",
            "Color masks (RGB): red=Window, green=Wall, blue=Roof, white=Other. "
            "All **740 paired 2048×2048** tiles in `data.zip` are split **80 / 10 / 10** "
            "(train / val / test, seed 42). Training uses random **1024×1024** crops; "
            "val/test metrics use **sliding-window on native 2048** (no 512 upsample).\n",
            "\n",
            "**Drive layout**:\n",
            "\n",
            "| Path | Content |\n",
            "|------|----------|\n",
            "| `My Drive/WWR_Seg_Model/data.zip` | All 740 image+mask pairs at **2048×2048** |\n",
            "| `/content/data/` | Local cache (fast I/O) |\n",
            "| `My Drive/WWR_Seg_Model/models/` | Saved models |\n",
            "| `My Drive/WWR_Seg_Model/results/unet/` | Split list, plots, CSV, paper table |\n",
            "\n",
            "1. **Runtime → A100 GPU**\n",
            "2. Run all cells in order (this split **requires a new training run**; do not reuse v1.10 weights)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            f"VERSION = '{VERSION}'\n",
            "print('U-Net + MobileNetV2  |  VERSION', VERSION)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "!pip install -q \"tensorflow>=2.15\" opencv-python-headless scikit-learn tqdm matplotlib pandas tabulate\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import os\n",
            "import shutil\n",
            "import zipfile\n",
            "from pathlib import Path\n",
            "\n",
            "from google.colab import drive\n",
            "\n",
            "if not Path('/content/drive/MyDrive').exists():\n",
            "    drive.mount('/content/drive')\n",
            "\n",
            "DRIVE_BASE = Path('/content/drive/MyDrive/WWR_Seg_Model')\n",
            "DATA_ZIP = DRIVE_BASE / 'data.zip'\n",
            "LOCAL_DATA = Path('/content/data')\n",
            "MODELS_DIR = DRIVE_BASE / 'models'\n",
            "RESULTS_DIR = DRIVE_BASE / 'results' / 'unet'\n",
            "\n",
            "MODELS_DIR.mkdir(parents=True, exist_ok=True)\n",
            "RESULTS_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "print('Notebook VERSION:', VERSION)\n",
            "print('Drive base :', DRIVE_BASE)\n",
            "print('Data zip   :', DATA_ZIP, 'exists=', DATA_ZIP.exists())\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.tif', '.tiff'}\n",
            "\n",
            "\n",
            "def _count_images(folder: Path) -> int:\n",
            "    if not folder.exists():\n",
            "        return 0\n",
            "    return sum(1 for f in folder.iterdir() if f.suffix.lower() in IMAGE_EXTS)\n",
            "\n",
            "\n",
            "def prepare_local_data(force: bool = False) -> tuple[Path, Path]:\n",
            "    \"\"\"Unzip data.zip to /content/data and normalize to train/images + train/masks.\"\"\"\n",
            "    train_img = LOCAL_DATA / 'train' / 'images'\n",
            "    train_msk = LOCAL_DATA / 'train' / 'masks'\n",
            "    if not force and train_img.exists() and _count_images(train_img) > 0:\n",
            "        print('Using cached local data:', train_img)\n",
            "        return train_img, train_msk\n",
            "\n",
            "    if not DATA_ZIP.exists():\n",
            "        raise FileNotFoundError(f'Upload data.zip to {DATA_ZIP}')\n",
            "\n",
            "    tmp = LOCAL_DATA / '_zip_extract'\n",
            "    if tmp.exists():\n",
            "        shutil.rmtree(tmp)\n",
            "    tmp.mkdir(parents=True)\n",
            "\n",
            "    print('Extracting', DATA_ZIP)\n",
            "    with zipfile.ZipFile(DATA_ZIP, 'r') as zf:\n",
            "        zf.extractall(tmp)\n",
            "\n",
            "    flat_img = tmp / 'images'\n",
            "    flat_msk = tmp / 'masks'\n",
            "    if flat_img.exists() and flat_msk.exists():\n",
            "        train_img.parent.mkdir(parents=True, exist_ok=True)\n",
            "        shutil.rmtree(LOCAL_DATA / 'train', ignore_errors=True)\n",
            "        shutil.copytree(flat_img, train_img)\n",
            "        shutil.copytree(flat_msk, train_msk)\n",
            "    elif (tmp / 'train' / 'images').exists():\n",
            "        shutil.rmtree(LOCAL_DATA, ignore_errors=True)\n",
            "        shutil.copytree(tmp, LOCAL_DATA)\n",
            "    else:\n",
            "        raise FileNotFoundError('Expected images/ + masks/ or train/images inside data.zip')\n",
            "\n",
            "    shutil.rmtree(tmp, ignore_errors=True)\n",
            "    print('Paired tiles on disk:', _count_images(train_img))\n",
            "    return train_img, train_msk\n",
            "\n",
            "\n",
            "images_dir, masks_dir = prepare_local_data(force=False)\n",
            "print('All 2048 tiles (to be split train/val/test):', images_dir)\n",
            "print('Masks:', masks_dir)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import cv2\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import tqdm\n",
            "import tensorflow as tf\n",
            "from matplotlib import pyplot as plt\n",
            "from sklearn.model_selection import train_test_split\n",
            "from tensorflow.keras import Model, Input\n",
            "from tensorflow.keras.applications import MobileNetV2\n",
            "from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess\n",
            "from tensorflow.keras.layers import (\n",
            "    BatchNormalization, Concatenate, Conv2D, Conv2DTranspose, Dropout,\n",
            "    GlobalAveragePooling2D, ReLU, Resizing,\n",
            ")\n",
            "from tensorflow.keras.metrics import MeanIoU\n",
            "\n",
            "tf.keras.mixed_precision.set_global_policy('float32')\n",
            "tf.config.optimizer.set_jit(False)\n",
            "\n",
            "OUTPUT_CHANNELS = 4\n",
            "FULL_SIZE = 2048   # native tile size on disk (images AND masks)\n",
            "CROP_SIZE = 1024   # model input; random crop in train, sliding window at test\n",
            "SIZE_X = CROP_SIZE\n",
            "SIZE_Y = CROP_SIZE\n",
            "SPLIT_SEED = 42\n",
            "TEST_FRACTION = 0.10\n",
            "VAL_FRACTION = 0.10  # of the full 740, not of the remainder\n",
            "CLASS_NAMES = ('Roof', 'Window', 'Wall', 'Other')\n",
            "TABLE_NAMES = ('Windows', 'Walls', 'Roofs', 'Other')\n",
            "TABLE_INDICES = (1, 2, 0, 3)  # Window, Wall, Roof, Other\n",
            "CLASS_WEIGHTS_NP = np.array([1.0, 3.5, 2.5, 0.5], dtype=np.float32)  # Roof, Window, Wall, Other\n",
            "FOCAL_ALPHA = (0.15, 0.40, 0.35, 0.10)\n",
            "DROPOUT_RATE = 0.30\n",
            "L2_WEIGHT = 1e-4\n",
            "FINE_TUNE_AT = 80\n",
            "\n",
            "CLASS_LUT = np.full(256, 3, dtype=np.int32)  # grayscale fallback; unknown → Other\n",
            "CLASS_LUT[72] = 0\n",
            "CLASS_LUT[128] = 1\n",
            "CLASS_LUT[220] = 2\n",
            "CLASS_LUT[255] = 3\n",
            "# RGB color masks in data/2048/masks (OpenCV loads BGR; convert first)\n",
            "RGB_WINDOW = (255, 0, 0)\n",
            "RGB_WALL = (0, 255, 0)\n",
            "RGB_ROOF = (0, 0, 255)\n",
            "RGB_OTHER = (255, 255, 255)\n",
            "\n",
            "\n",
            "def pair_image_mask_paths(img_dir: Path, mask_dir: Path) -> list[tuple[str, str]]:\n",
            "    pairs = []\n",
            "    for img_path in sorted(img_dir.iterdir()):\n",
            "        if img_path.suffix.lower() not in {'.png', '.jpg', '.jpeg'}:\n",
            "            continue\n",
            "        stem = img_path.stem\n",
            "        mask_stem = stem.replace('_texture', '_mask') if stem.endswith('_texture') else f'{stem}_mask'\n",
            "        mask_path = None\n",
            "        for ext in (img_path.suffix, '.png', '.jpg', '.jpeg'):\n",
            "            candidate = mask_dir / f'{mask_stem}{ext}'\n",
            "            if candidate.exists():\n",
            "                mask_path = candidate\n",
            "                break\n",
            "            same_name = mask_dir / f'{stem}{ext}'\n",
            "            if same_name.exists():\n",
            "                mask_path = same_name\n",
            "                break\n",
            "        if mask_path is None:\n",
            "            raise FileNotFoundError(f'No mask for {img_path.name}')\n",
            "        pairs.append((str(img_path), str(mask_path)))\n",
            "    return pairs\n",
            "\n",
            "\n",
            "def load_rgb(path: str, size: int = FULL_SIZE) -> np.ndarray:\n",
            "    bgr = cv2.imread(path, cv2.IMREAD_COLOR)\n",
            "    if bgr is None:\n",
            "        raise FileNotFoundError(path)\n",
            "    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\n",
            "    if rgb.shape[0] != size or rgb.shape[1] != size:\n",
            "        rgb = cv2.resize(rgb, (size, size), interpolation=cv2.INTER_LINEAR)\n",
            "    return rgb.astype(np.float32) / 255.0\n",
            "\n",
            "\n",
            "def color_mask_to_class(rgb: np.ndarray) -> np.ndarray:\n",
            "    \"\"\"Map RGB mask to {Roof=0, Window=1, Wall=2, Other=3}.\"\"\"\n",
            "    out = np.full(rgb.shape[:2], 3, dtype=np.int32)\n",
            "    out[np.all(rgb == RGB_ROOF, axis=-1)] = 0\n",
            "    out[np.all(rgb == RGB_WINDOW, axis=-1)] = 1\n",
            "    out[np.all(rgb == RGB_WALL, axis=-1)] = 2\n",
            "    out[np.all(rgb == RGB_OTHER, axis=-1)] = 3\n",
            "    return out\n",
            "\n",
            "\n",
            "def load_mask(path: str, size: int = FULL_SIZE) -> np.ndarray:\n",
            "    mask = cv2.imread(path, cv2.IMREAD_UNCHANGED)\n",
            "    if mask is None:\n",
            "        raise FileNotFoundError(path)\n",
            "    if mask.ndim == 3:\n",
            "        rgb = cv2.cvtColor(mask[..., :3], cv2.COLOR_BGR2RGB)\n",
            "        if rgb.shape[0] != size or rgb.shape[1] != size:\n",
            "            rgb = cv2.resize(rgb, (size, size), interpolation=cv2.INTER_NEAREST)\n",
            "        return color_mask_to_class(rgb)\n",
            "    if mask.shape[0] != size or mask.shape[1] != size:\n",
            "        mask = cv2.resize(mask, (size, size), interpolation=cv2.INTER_NEAREST)\n",
            "    return CLASS_LUT[mask].astype(np.int32)\n",
            "\n",
            "\n",
            "pairs = pair_image_mask_paths(images_dir, masks_dir)\n",
            "print(f'Paired 2048 tiles: {len(pairs)}')\n",
            "print('First pair:', pairs[0])\n",
            "probe = cv2.imread(pairs[0][0])\n",
            "print('Native image HW:', None if probe is None else probe.shape[:2], '| expected', FULL_SIZE)\n",
            "if probe is not None and min(probe.shape[:2]) < 1500:\n",
            "    print('WARNING: files look smaller than 2048. Replace data.zip with native 2048 PNG tiles')\n",
            "    print('         and re-run prepare_local_data(force=True) after deleting /content/data.')\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "trainval_pairs, test_pairs = train_test_split(\n",
            "    pairs, test_size=TEST_FRACTION, random_state=SPLIT_SEED, shuffle=True\n",
            ")\n",
            "val_of_remaining = VAL_FRACTION / (1.0 - TEST_FRACTION)\n",
            "train_pairs, val_pairs = train_test_split(\n",
            "    trainval_pairs, test_size=val_of_remaining, random_state=SPLIT_SEED, shuffle=True\n",
            ")\n",
            "assert not set(train_pairs) & set(val_pairs)\n",
            "assert not set(train_pairs) & set(test_pairs)\n",
            "assert not set(val_pairs) & set(test_pairs)\n",
            "print(\n",
            "    f'Split {len(pairs)} native {FULL_SIZE} tiles  '\n",
            "    f'(seed={SPLIT_SEED}, {int((1 - VAL_FRACTION - TEST_FRACTION) * 100)}/'\n",
            "    f'{int(VAL_FRACTION * 100)}/{int(TEST_FRACTION * 100)}):'\n",
            ")\n",
            "print('  Train:', len(train_pairs), '| Val:', len(val_pairs), '| Test:', len(test_pairs))\n",
            "print('Files stay on disk at', FULL_SIZE, 'px; the model sees', CROP_SIZE, 'px crops.')\n",
            "print('Do not load v1.10 weights: that run trained on a 90/10 split with no held-out 2048 test.')\n",
            "\n",
            "split_rows = []\n",
            "for name, file_pairs in (('train', train_pairs), ('val', val_pairs), ('test', test_pairs)):\n",
            "    for ip, mp in file_pairs:\n",
            "        split_rows.append({'split': name, 'image': Path(ip).name, 'mask': Path(mp).name})\n",
            "split_df = pd.DataFrame(split_rows)\n",
            "split_path = RESULTS_DIR / 'split_740_2048.csv'\n",
            "split_df.to_csv(split_path, index=False)\n",
            "print('Saved split list:', split_path)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "LUT_TF = tf.constant(CLASS_LUT, dtype=tf.int32)\n",
            "\n",
            "\n",
            "def decode_pair(img_path, mask_path):\n",
            "    img = tf.io.decode_image(tf.io.read_file(img_path), channels=3, expand_animations=False)\n",
            "    img.set_shape([None, None, 3])\n",
            "    img = tf.image.convert_image_dtype(img, tf.float32)\n",
            "    img = tf.image.resize(img, [FULL_SIZE, FULL_SIZE], method='bilinear')\n",
            "\n",
            "    mask = tf.io.decode_image(tf.io.read_file(mask_path), channels=3, expand_animations=False)\n",
            "    mask.set_shape([None, None, 3])\n",
            "    r = tf.cast(mask[..., 0], tf.int32)\n",
            "    g = tf.cast(mask[..., 1], tf.int32)\n",
            "    b = tf.cast(mask[..., 2], tf.int32)\n",
            "    cls = tf.fill(tf.shape(r), 3)\n",
            "    cls = tf.where((r == 0) & (g == 0) & (b == 255), 0, cls)   # Roof blue\n",
            "    cls = tf.where((r == 255) & (g == 0) & (b == 0), 1, cls)   # Window red\n",
            "    cls = tf.where((r == 0) & (g == 255) & (b == 0), 2, cls)   # Wall green\n",
            "    mask = tf.image.resize(\n",
            "        tf.expand_dims(tf.cast(cls, tf.float32), -1),\n",
            "        [FULL_SIZE, FULL_SIZE],\n",
            "        method='nearest',\n",
            "    )\n",
            "    mask = tf.cast(tf.squeeze(mask, -1), tf.int32)\n",
            "    return img, mask\n",
            "\n",
            "\n",
            "def random_crop_pair(image, mask):\n",
            "    stacked = tf.concat([image, tf.cast(mask[..., tf.newaxis], tf.float32)], axis=-1)\n",
            "    stacked = tf.image.random_crop(stacked, [CROP_SIZE, CROP_SIZE, 4])\n",
            "    return stacked[..., :3], tf.cast(stacked[..., 3], tf.int32)\n",
            "\n",
            "\n",
            "def center_crop_pair(image, mask):\n",
            "    off = (FULL_SIZE - CROP_SIZE) // 2\n",
            "    return image[off:off + CROP_SIZE, off:off + CROP_SIZE], mask[off:off + CROP_SIZE, off:off + CROP_SIZE]\n",
            "\n",
            "\n",
            "def augment(image, mask):\n",
            "    mask = tf.cast(mask, tf.int32)\n",
            "    if tf.random.uniform(()) > 0.5:\n",
            "        image = tf.image.flip_left_right(image)\n",
            "        mask = tf.image.flip_left_right(tf.expand_dims(mask, -1))[..., 0]\n",
            "    image = tf.image.random_brightness(image, max_delta=0.15)\n",
            "    image = tf.image.random_contrast(image, 0.85, 1.15)\n",
            "    image = tf.image.random_saturation(image, 0.85, 1.15)\n",
            "    noise = tf.random.normal(tf.shape(image), stddev=0.02, dtype=image.dtype)\n",
            "    image = tf.clip_by_value(image + noise, 0.0, 1.0)\n",
            "    return image, mask\n",
            "\n",
            "\n",
            "def apply_backbone_preprocess(image, mask):\n",
            "    image = mobilenet_preprocess(image * 255.0)\n",
            "    return image, mask\n",
            "\n",
            "\n",
            "def build_dataset(file_pairs, training=True, batch_size=4):\n",
            "    img_p = [p[0] for p in file_pairs]\n",
            "    msk_p = [p[1] for p in file_pairs]\n",
            "    ds = tf.data.Dataset.from_tensor_slices((img_p, msk_p))\n",
            "    ds = ds.map(decode_pair, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    if training:\n",
            "        ds = ds.shuffle(len(file_pairs)).map(random_crop_pair, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "        ds = ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    else:\n",
            "        ds = ds.map(center_crop_pair, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    ds = ds.map(apply_backbone_preprocess, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "CLASS_WEIGHTS = tf.constant(CLASS_WEIGHTS_NP, dtype=tf.float32)\n",
            "\n",
            "\n",
            "def conv_block(x, filters, dropout_rate=DROPOUT_RATE, l2=L2_WEIGHT):\n",
            "    for _ in range(2):\n",
            "        x = Conv2D(\n",
            "            filters, 3, padding='same', use_bias=False,\n",
            "            kernel_regularizer=tf.keras.regularizers.l2(l2),\n",
            "        )(x)\n",
            "        x = BatchNormalization()(x)\n",
            "        x = ReLU()(x)\n",
            "    return Dropout(dropout_rate)(x)\n",
            "\n",
            "\n",
            "def upsample_block(filters, size=3):\n",
            "    return tf.keras.Sequential([\n",
            "        Conv2DTranspose(filters, size, strides=2, padding='same', use_bias=False),\n",
            "        BatchNormalization(),\n",
            "        ReLU(),\n",
            "    ])\n",
            "\n",
            "\n",
            "def aspp_block(x, filters=256, rates=(6, 12)):\n",
            "    branches = []\n",
            "    b = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "               kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "    b = BatchNormalization()(b)\n",
            "    branches.append(ReLU()(b))\n",
            "    for rate in rates:\n",
            "        b = Conv2D(filters, 3, padding='same', dilation_rate=rate, use_bias=False,\n",
            "                   kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "        b = BatchNormalization()(b)\n",
            "        branches.append(ReLU()(b))\n",
            "    gap = GlobalAveragePooling2D(keepdims=True)(x)\n",
            "    gap = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "                 kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(gap)\n",
            "    gap = BatchNormalization()(gap)\n",
            "    gap = ReLU()(gap)\n",
            "    gap = Resizing(int(x.shape[1]), int(x.shape[2]), interpolation='bilinear')(gap)\n",
            "    branches.append(gap)\n",
            "    x = Concatenate()(branches)\n",
            "    x = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "               kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "    x = BatchNormalization()(x)\n",
            "    return ReLU()(x)\n",
            "\n",
            "\n",
            "def weighted_dice_loss(y_true, y_pred, smooth=1e-6):\n",
            "    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS)\n",
            "    y_pred = tf.cast(y_pred, tf.float32)\n",
            "    intersection = tf.reduce_sum(y_true_oh * y_pred, axis=[0, 1, 2])\n",
            "    denom = tf.reduce_sum(y_true_oh, axis=[0, 1, 2]) + tf.reduce_sum(y_pred, axis=[0, 1, 2])\n",
            "    dice = (2.0 * intersection + smooth) / (denom + smooth)\n",
            "    return 1.0 - tf.reduce_sum(dice * CLASS_WEIGHTS) / tf.reduce_sum(CLASS_WEIGHTS)\n",
            "\n",
            "\n",
            "def focal_loss(y_true, y_pred, gamma=2.0):\n",
            "    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS)\n",
            "    y_pred = tf.clip_by_value(tf.cast(y_pred, tf.float32), 1e-7, 1.0 - 1e-7)\n",
            "    ce = -y_true_oh * tf.math.log(y_pred)\n",
            "    alpha = tf.reshape(tf.constant(FOCAL_ALPHA, dtype=tf.float32), (1, 1, 1, -1))\n",
            "    weight = alpha * y_true_oh * tf.pow(1.0 - y_pred, gamma)\n",
            "    return tf.reduce_mean(tf.reduce_sum(weight * ce, axis=-1))\n",
            "\n",
            "\n",
            "def boundary_loss(y_true, y_pred):\n",
            "    y_true_oh = tf.cast(tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS), tf.float32)\n",
            "    y_pred = tf.cast(y_pred, tf.float32)\n",
            "    sobel = tf.image.sobel_edges(y_true_oh)\n",
            "    edges = tf.sqrt(tf.reduce_sum(tf.square(sobel), axis=-1) + 1e-6)\n",
            "    edges = tf.clip_by_value(edges, 0.0, 1.0)\n",
            "    ce = -y_true_oh * tf.math.log(tf.clip_by_value(y_pred, 1e-7, 1.0))\n",
            "    return tf.reduce_mean(tf.reduce_sum(ce * (1.0 + 3.0 * edges), axis=-1))\n",
            "\n",
            "\n",
            "def combined_loss(y_true, y_pred):\n",
            "    return (\n",
            "        0.50 * weighted_dice_loss(y_true, y_pred)\n",
            "        + 0.35 * focal_loss(y_true, y_pred)\n",
            "        + 0.15 * boundary_loss(y_true, y_pred)\n",
            "    )\n",
            "\n",
            "\n",
            "class MeanIoUFromLogits(MeanIoU):\n",
            "    \"\"\"MeanIoU for softmax output — argmax predictions before update.\"\"\"\n",
            "\n",
            "    def update_state(self, y_true, y_pred, sample_weight=None):\n",
            "        y_true = tf.cast(y_true, tf.int32)\n",
            "        y_pred = tf.cast(tf.argmax(y_pred, axis=-1), tf.int32)\n",
            "        return super().update_state(y_true, y_pred, sample_weight)\n",
            "\n",
            "\n",
            "class ClassIoU(tf.keras.metrics.Metric):\n",
            "    def __init__(self, class_id, name, **kwargs):\n",
            "        super().__init__(name=name, **kwargs)\n",
            "        self.class_id = int(class_id)\n",
            "        self.tp = self.add_weight(name='tp', initializer='zeros')\n",
            "        self.fp = self.add_weight(name='fp', initializer='zeros')\n",
            "        self.fn = self.add_weight(name='fn', initializer='zeros')\n",
            "\n",
            "    def update_state(self, y_true, y_pred, sample_weight=None):\n",
            "        y_true = tf.cast(y_true, tf.int32)\n",
            "        y_pred = tf.cast(tf.argmax(y_pred, axis=-1), tf.int32)\n",
            "        true_c = tf.equal(y_true, self.class_id)\n",
            "        pred_c = tf.equal(y_pred, self.class_id)\n",
            "        self.tp.assign_add(tf.reduce_sum(tf.cast(tf.logical_and(true_c, pred_c), tf.float32)))\n",
            "        self.fp.assign_add(tf.reduce_sum(tf.cast(tf.logical_and(tf.logical_not(true_c), pred_c), tf.float32)))\n",
            "        self.fn.assign_add(tf.reduce_sum(tf.cast(tf.logical_and(true_c, tf.logical_not(pred_c)), tf.float32)))\n",
            "\n",
            "    def result(self):\n",
            "        return self.tp / (self.tp + self.fp + self.fn + 1e-6)\n",
            "\n",
            "    def reset_state(self):\n",
            "        self.tp.assign(0.0)\n",
            "        self.fp.assign(0.0)\n",
            "        self.fn.assign(0.0)\n",
            "\n",
            "\n",
            "def unet_model(output_channels=4, dropout_rate=DROPOUT_RATE):\n",
            "    h, w, c = SIZE_Y, SIZE_X, 3\n",
            "    base = MobileNetV2(input_shape=[h, w, c], include_top=False, weights='imagenet')\n",
            "    layer_names = [\n",
            "        'block_1_expand_relu', 'block_3_expand_relu', 'block_6_expand_relu',\n",
            "        'block_13_expand_relu', 'block_16_project',\n",
            "    ]\n",
            "    down_stack = Model(base.input, [base.get_layer(n).output for n in layer_names], name='mobilenetv2_encoder')\n",
            "    down_stack.trainable = False\n",
            "\n",
            "    decoder_filters = (256, 128, 64, 32)\n",
            "    up_stack = [upsample_block(f) for f in decoder_filters]\n",
            "\n",
            "    inputs = Input(shape=[h, w, c], name='input_image')\n",
            "    skips = down_stack(inputs)\n",
            "    x = aspp_block(skips[-1], filters=256)\n",
            "    for up, skip, filt in zip(up_stack, reversed(skips[:-1]), decoder_filters):\n",
            "        skip = Conv2D(filt, 1, padding='same', use_bias=False)(skip)\n",
            "        skip = BatchNormalization()(skip)\n",
            "        skip = ReLU()(skip)\n",
            "        x = up(x)\n",
            "        x = Concatenate()([x, skip])\n",
            "        x = conv_block(x, filt, dropout_rate)\n",
            "    x = Conv2DTranspose(output_channels, 3, strides=2, padding='same', dtype='float32')(x)\n",
            "    outputs = tf.keras.layers.Activation('softmax', dtype='float32', name='mask')(x)\n",
            "    return Model(inputs, outputs, name='unet_mobilenetv2'), down_stack\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def create_mask(pred_mask):\n",
            "    return tf.argmax(pred_mask, axis=-1)[0].numpy()\n",
            "\n",
            "\n",
            "def show_predictions(epoch, tag='train'):\n",
            "    for xb, yb in val_ds.take(1):\n",
            "        pred = np.argmax(model.predict(xb[:1], verbose=0), axis=-1)[0]\n",
            "        vis = np.clip((xb[0].numpy() + 1.0) * 0.5, 0.0, 1.0)\n",
            "        gt = yb[0].numpy()\n",
            "        fig = plt.figure(figsize=(12, 4))\n",
            "        for col, (title, arr) in enumerate([\n",
            "            ('Input (1024 crop)', vis),\n",
            "            ('Ground Truth', gt),\n",
            "            ('Prediction', pred),\n",
            "        ]):\n",
            "            ax = fig.add_subplot(1, 3, col + 1)\n",
            "            ax.imshow(arr if col == 0 else arr, cmap=None if col == 0 else 'jet', vmin=0, vmax=3 if col else None)\n",
            "            ax.set_title(title)\n",
            "            ax.axis('off')\n",
            "        fig.suptitle(f'{tag} · epoch {epoch + 1}')\n",
            "        fig.savefig(RESULTS_DIR / f'{tag}_epoch_{epoch + 1:03d}.png', dpi=100, bbox_inches='tight')\n",
            "        plt.show()\n",
            "        plt.close(fig)\n",
            "        break\n",
            "\n",
            "\n",
            "class DisplayCallback(tf.keras.callbacks.Callback):\n",
            "    def __init__(self, every_n=5, tag='stage'):\n",
            "        super().__init__()\n",
            "        self.every_n = every_n\n",
            "        self.tag = tag\n",
            "\n",
            "    def on_epoch_end(self, epoch, logs=None):\n",
            "        if (epoch + 1) % self.every_n == 0 or epoch == 0:\n",
            "            show_predictions(epoch, tag=self.tag)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def train_metrics():\n",
            "    return [\n",
            "        tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy'),\n",
            "        MeanIoUFromLogits(num_classes=OUTPUT_CHANNELS, name='mean_iou'),\n",
            "        ClassIoU(1, name='iou_window'),\n",
            "        ClassIoU(2, name='iou_wall'),\n",
            "    ]\n",
            "\n",
            "\n",
            "def make_optimizer(lr):\n",
            "    kwargs = dict(learning_rate=lr, weight_decay=1e-5, clipnorm=1.0)\n",
            "    try:\n",
            "        return tf.keras.optimizers.AdamW(**kwargs, use_ema=True, ema_momentum=0.999)\n",
            "    except TypeError:\n",
            "        return tf.keras.optimizers.AdamW(**kwargs)\n",
            "\n",
            "\n",
            "def compile_model(lr):\n",
            "    model.compile(\n",
            "        optimizer=make_optimizer(lr),\n",
            "        loss=combined_loss,\n",
            "        metrics=train_metrics(),\n",
            "        jit_compile=False,\n",
            "    )\n",
            "\n",
            "\n",
            "model, down_stack = unet_model(OUTPUT_CHANNELS, dropout_rate=DROPOUT_RATE)\n",
            "compile_model(1e-3)\n",
            "model.summary()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "BATCH_SIZE = 4  # 1024 crops; raise to 8 on 80GB GPUs if memory allows\n",
            "STAGE1_EPOCHS = 20\n",
            "STAGE2_EPOCHS = 80\n",
            "CHECKPOINT_MONITOR = 'val_iou_window'\n",
            "checkpoint_path = MODELS_DIR / f'unet_mobilenetv2_v{VERSION}.keras'\n",
            "\n",
            "train_ds = build_dataset(train_pairs, training=True, batch_size=BATCH_SIZE)\n",
            "val_ds = build_dataset(val_pairs, training=False, batch_size=BATCH_SIZE)\n",
            "steps_per_epoch = int(np.ceil(len(train_pairs) / BATCH_SIZE))\n",
            "\n",
            "def make_callbacks(tag, patience):\n",
            "    cbs = [\n",
            "        DisplayCallback(every_n=5, tag=tag),\n",
            "        tf.keras.callbacks.ModelCheckpoint(\n",
            "            str(checkpoint_path), monitor=CHECKPOINT_MONITOR, mode='max',\n",
            "            save_best_only=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.EarlyStopping(\n",
            "            monitor=CHECKPOINT_MONITOR, mode='max', patience=patience,\n",
            "            restore_best_weights=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.ReduceLROnPlateau(\n",
            "            monitor=CHECKPOINT_MONITOR, mode='max', factor=0.5, patience=5,\n",
            "            min_lr=1e-7, verbose=1,\n",
            "        ),\n",
            "    ]\n",
            "    return cbs\n",
            "\n",
            "print('Stage 1: frozen MobileNetV2 encoder, train decoder')\n",
            "history1 = model.fit(\n",
            "    train_ds, validation_data=val_ds, epochs=STAGE1_EPOCHS,\n",
            "    callbacks=make_callbacks('stage1', patience=8),\n",
            ")\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "print('Stage 2: fine-tune encoder from layer', FINE_TUNE_AT, '(BatchNorm stays frozen)')\n",
            "if checkpoint_path.exists():\n",
            "    model.load_weights(str(checkpoint_path))\n",
            "    print('Loaded best Stage-1 weights')\n",
            "down_stack.trainable = True\n",
            "for i, layer in enumerate(down_stack.layers):\n",
            "    if isinstance(layer, BatchNormalization):\n",
            "        layer.trainable = False\n",
            "    else:\n",
            "        layer.trainable = i >= FINE_TUNE_AT\n",
            "\n",
            "cosine = tf.keras.optimizers.schedules.CosineDecay(\n",
            "    initial_learning_rate=3e-5,\n",
            "    decay_steps=max(steps_per_epoch * STAGE2_EPOCHS, 1),\n",
            "    alpha=0.01,\n",
            ")\n",
            "model.compile(\n",
            "    optimizer=make_optimizer(cosine),\n",
            "    loss=combined_loss,\n",
            "    metrics=train_metrics(),\n",
            "    jit_compile=False,\n",
            ")\n",
            "\n",
            "history2 = model.fit(\n",
            "    train_ds, validation_data=val_ds, epochs=STAGE2_EPOCHS,\n",
            "    callbacks=[\n",
            "        DisplayCallback(every_n=5, tag='stage2'),\n",
            "        tf.keras.callbacks.ModelCheckpoint(\n",
            "            str(checkpoint_path), monitor=CHECKPOINT_MONITOR, mode='max',\n",
            "            save_best_only=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.EarlyStopping(\n",
            "            monitor=CHECKPOINT_MONITOR, mode='max', patience=15,\n",
            "            restore_best_weights=True, verbose=1,\n",
            "        ),\n",
            "    ],\n",
            ")\n",
            "print('Best model →', checkpoint_path)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def merge_history(*histories):\n",
            "    merged = {}\n",
            "    for h in histories:\n",
            "        for k, v in h.history.items():\n",
            "            merged.setdefault(k, []).extend(v)\n",
            "    return merged\n",
            "\n",
            "\n",
            "hist = merge_history(history1, history2)\n",
            "iou_key = 'mean_iou' if 'mean_iou' in hist else 'mean_io_u'\n",
            "plt.figure(figsize=(7, 4))\n",
            "plt.plot(hist[iou_key], label='train IoU')\n",
            "plt.plot(hist['val_' + iou_key], label='val IoU')\n",
            "plt.axvline(len(history1.history[iou_key]) - 0.5, color='gray', ls='--', lw=1, label='fine-tune start')\n",
            "plt.xlabel('Epoch')\n",
            "plt.ylabel('Mean IoU')\n",
            "plt.legend()\n",
            "plt.tight_layout()\n",
            "plt.savefig(RESULTS_DIR / 'training_curve.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Test-set class-wise metrics\n",
            "\n",
            "Pixel-wise Precision, Recall, F1-score, and IoU with **sliding-window** "
            "inference on the held-out **2048×2048 test tiles** (10% of the 740 pairs, never used in training).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def predict_sliding(image: np.ndarray, crop=CROP_SIZE, stride=None, tta=True) -> np.ndarray:\n",
            "    if stride is None:\n",
            "        stride = (crop * 3) // 4\n",
            "    h, w, _ = image.shape\n",
            "    acc = np.zeros((h, w, OUTPUT_CHANNELS), np.float32)\n",
            "    cnt = np.zeros((h, w, 1), np.float32)\n",
            "    ys = list(range(0, max(h - crop, 0) + 1, stride))\n",
            "    xs = list(range(0, max(w - crop, 0) + 1, stride))\n",
            "    if ys[-1] != h - crop:\n",
            "        ys.append(h - crop)\n",
            "    if xs[-1] != w - crop:\n",
            "        xs.append(w - crop)\n",
            "    for y in ys:\n",
            "        for x in xs:\n",
            "            patch = image[y:y + crop, x:x + crop]\n",
            "            probs = model.predict(mobilenet_preprocess(patch[np.newaxis, ...] * 255.0), verbose=0)[0]\n",
            "            if tta:\n",
            "                flipped = patch[:, ::-1]\n",
            "                probs_f = model.predict(mobilenet_preprocess(flipped[np.newaxis, ...] * 255.0), verbose=0)[0][:, ::-1]\n",
            "                probs = 0.5 * (probs + probs_f)\n",
            "            acc[y:y + crop, x:x + crop] += probs\n",
            "            cnt[y:y + crop, x:x + crop] += 1.0\n",
            "    return np.argmax(acc / np.maximum(cnt, 1e-6), axis=-1).astype(np.int32)\n",
            "\n",
            "\n",
            "def load_eval_pairs(file_pairs):\n",
            "    xs, ys = [], []\n",
            "    for ip, mp in tqdm.tqdm(file_pairs, desc='Loading full-res tiles'):\n",
            "        xs.append(load_rgb(ip, FULL_SIZE))\n",
            "        ys.append(load_mask(mp, FULL_SIZE))\n",
            "    return xs, ys\n",
            "\n",
            "\n",
            "def confusion_matrix(y_true: np.ndarray, y_pred: np.ndarray, num_classes=4) -> np.ndarray:\n",
            "    t = y_true.ravel().astype(np.int32)\n",
            "    p = y_pred.ravel().astype(np.int32)\n",
            "    valid = (t >= 0) & (t < num_classes) & (p >= 0) & (p < num_classes)\n",
            "    return np.bincount(t[valid] * num_classes + p[valid], minlength=num_classes * num_classes).reshape(num_classes, num_classes)\n",
            "\n",
            "\n",
            "def classwise_table(cm: np.ndarray) -> pd.DataFrame:\n",
            "    rows = []\n",
            "    for display_name, idx in zip(TABLE_NAMES, TABLE_INDICES):\n",
            "        tp = cm[idx, idx]\n",
            "        fp = cm[:, idx].sum() - tp\n",
            "        fn = cm[idx, :].sum() - tp\n",
            "        precision = tp / (tp + fp + 1e-6)\n",
            "        recall = tp / (tp + fn + 1e-6)\n",
            "        f1 = 2 * precision * recall / (precision + recall + 1e-6)\n",
            "        iou = tp / (tp + fp + fn + 1e-6)\n",
            "        rows.append({\n",
            "            'Class': display_name,\n",
            "            'Precision': float(precision),\n",
            "            'Recall': float(recall),\n",
            "            'F1-score': float(f1),\n",
            "            'IoU': float(iou),\n",
            "        })\n",
            "    df = pd.DataFrame(rows)\n",
            "    mean = df[['Precision', 'Recall', 'F1-score', 'IoU']].mean()\n",
            "    df.loc[len(df)] = ['Mean', mean['Precision'], mean['Recall'], mean['F1-score'], mean['IoU']]\n",
            "    return df\n",
            "\n",
            "\n",
            "eval_split = 'test'\n",
            "eval_pairs = test_pairs\n",
            "print(f'Held-out 2048 test tiles: {len(eval_pairs)} (from the same 740 as train/val; no 512 test set)')\n",
            "\n",
            "X_eval, y_eval = load_eval_pairs(eval_pairs)\n",
            "print('Sliding-window inference on', FULL_SIZE, 'tiles with', CROP_SIZE, 'crops + TTA')\n",
            "y_hat = [predict_sliding(img, tta=True) for img in tqdm.tqdm(X_eval, desc='Predict')]\n",
            "y_eval = np.stack(y_eval, axis=0)\n",
            "y_hat = np.stack(y_hat, axis=0)\n",
            "cm = confusion_matrix(y_eval, y_hat)\n",
            "metrics_df = classwise_table(cm)\n",
            "metrics_df_fmt = metrics_df.copy()\n",
            "for col in ('Precision', 'Recall', 'F1-score', 'IoU'):\n",
            "    metrics_df_fmt[col] = metrics_df_fmt[col].map(lambda v: f'{v:.4f}')\n",
            "\n",
            "def dataframe_to_markdown(df: pd.DataFrame) -> str:\n",
            "    cols = list(df.columns)\n",
            "    lines = ['| ' + ' | '.join(cols) + ' |', '| ' + ' | '.join(['---'] * len(cols)) + ' |']\n",
            "    for row in df.itertuples(index=False):\n",
            "        lines.append('| ' + ' | '.join(str(v) for v in row) + ' |')\n",
            "    return '\\n'.join(lines)\n",
            "\n",
            "\n",
            "print()\n",
            "print(f'Table. Class-wise quantitative performance of the semantic segmentation model on the {eval_split} dataset.')\n",
            "print()\n",
            "print(metrics_df_fmt.to_string(index=False))\n",
            "print()\n",
            "print(dataframe_to_markdown(metrics_df_fmt))\n",
            "\n",
            "csv_path = RESULTS_DIR / f'classwise_metrics_{eval_split}.csv'\n",
            "md_path = RESULTS_DIR / f'classwise_metrics_{eval_split}.md'\n",
            "metrics_df.to_csv(csv_path, index=False, float_format='%.6f')\n",
            "md_path.write_text(\n",
            "    f'Table. Class-wise quantitative performance of the semantic segmentation model on the {eval_split} dataset.\\n\\n'\n",
            "    + dataframe_to_markdown(metrics_df_fmt)\n",
            "    + '\\n',\n",
            "    encoding='utf-8',\n",
            ")\n",
            "print('Saved', csv_path)\n",
            "print('Saved', md_path)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "fig, ax = plt.subplots(figsize=(8.5, 2.8))\n",
            "ax.axis('off')\n",
            "ax.set_title(\n",
            "    f'Table. Class-wise quantitative performance on the {eval_split} dataset',\n",
            "    fontsize=11, pad=8,\n",
            ")\n",
            "cell_text = [metrics_df_fmt.iloc[i].tolist() for i in range(len(metrics_df_fmt))]\n",
            "table = ax.table(\n",
            "    cellText=cell_text,\n",
            "    colLabels=list(metrics_df_fmt.columns),\n",
            "    loc='center',\n",
            "    cellLoc='center',\n",
            ")\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(10)\n",
            "table.scale(1.15, 1.45)\n",
            "for (r, c), cell in table.get_celld().items():\n",
            "    if r == 0:\n",
            "        cell.set_facecolor('#d9e2ef')\n",
            "        cell.set_text_props(weight='bold')\n",
            "    elif r == len(cell_text):\n",
            "        cell.set_facecolor('#eef2f7')\n",
            "        cell.set_text_props(weight='bold')\n",
            "plt.tight_layout()\n",
            "fig.savefig(RESULTS_DIR / f'classwise_table_{eval_split}.png', dpi=160, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(5, 4))\n",
            "im = ax.imshow(cm, cmap='Blues')\n",
            "ax.set_xticks(range(4), CLASS_NAMES, rotation=30, ha='right')\n",
            "ax.set_yticks(range(4), CLASS_NAMES)\n",
            "ax.set_xlabel('Predicted')\n",
            "ax.set_ylabel('Ground truth')\n",
            "for i in range(4):\n",
            "    for j in range(4):\n",
            "        ax.text(j, i, f'{cm[i, j]:,}', ha='center', va='center', fontsize=8)\n",
            "fig.colorbar(im, ax=ax, fraction=0.046)\n",
            "plt.tight_layout()\n",
            "fig.savefig(RESULTS_DIR / f'confusion_matrix_{eval_split}.png', dpi=140, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "n_show = min(3, len(X_eval))\n",
            "fig, axes = plt.subplots(n_show, 3, figsize=(12, 3.5 * n_show))\n",
            "if n_show == 1:\n",
            "    axes = np.expand_dims(axes, 0)\n",
            "for i in range(n_show):\n",
            "    axes[i, 0].imshow(np.clip(X_eval[i], 0, 1))\n",
            "    axes[i, 0].set_title('Input')\n",
            "    axes[i, 1].imshow(y_eval[i], cmap='jet', vmin=0, vmax=3)\n",
            "    axes[i, 1].set_title('Ground truth')\n",
            "    axes[i, 2].imshow(y_hat[i], cmap='jet', vmin=0, vmax=3)\n",
            "    axes[i, 2].set_title('Prediction')\n",
            "    for ax in axes[i]:\n",
            "        ax.axis('off')\n",
            "plt.tight_layout()\n",
            "plt.savefig(RESULTS_DIR / f'{eval_split}_samples.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
]


def _as_source(text: str) -> list[str]:
    if not text.endswith("\n"):
        text += "\n"
    return [text]


# Normalize sources that were written as lists of lines already
for cell in cells:
    src = cell["source"]
    if isinstance(src, str):
        cell["source"] = _as_source(src)

OUT = ROOT / "U_NET_Segmentation.ipynb"
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
        "colab": {"provenance": [], "gpuType": "A100"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

OUT.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print(f"Wrote {OUT} ({len(cells)} cells)")
