"""Regenerate U_NET_Segmentation.ipynb for Colab (512px, WWR_Seg_Model Drive paths)."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION = "1.4.0"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# U-Net + MobileNetV2 — v{VERSION} (A100, 512×512)\n",
            "\n",
            f"**Notebook version:** `{VERSION}` — bump this string on every GitHub push.\n",
            "\n",
            "Improved facade segmentation. **v1.4.0:** freeze encoder BatchNorm during fine-tune.\n",
            "\n",
            "**Drive layout** (same as `WWR_Seg_Model.ipynb`):\n",
            "\n",
            "| Path | Content |\n",
            "|------|----------|\n",
            "| `My Drive/WWR_Seg_Model/data.zip` | Training data |\n",
            "| `My Drive/WWR_Seg_Model/test.zip` or `test_images/` | Independent test set (images + masks) |\n",
            "| `/content/data/` | Local cache (fast I/O) |\n",
            "| `My Drive/WWR_Seg_Model/models/` | Saved models |\n",
            "| `My Drive/WWR_Seg_Model/results/unet/` | Plots, CSV, paper table |\n",
            "\n",
            "1. **Runtime → A100 GPU**\n",
            "2. Run all cells in order\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            f"VERSION = '{VERSION}'\n",
            "print('U-Net + MobileNetV2  |  VERSION', VERSION)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "!pip install -q \"tensorflow>=2.15\" opencv-python-headless scikit-learn tqdm matplotlib pandas tabulate\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import os\n",
            "import shutil\n",
            "import zipfile\n",
            "from pathlib import Path\n",
            "\n",
            "from google.colab import drive\n",
            "\n",
            "if not Path('/content/drive/MyDrive').exists():\n",
            "    drive.mount('/content/drive')\n",
            "\n",
            "DRIVE_BASE = Path('/content/drive/MyDrive/WWR_Seg_Model')\n",
            "DATA_ZIP = DRIVE_BASE / 'data.zip'\n",
            "TEST_ZIP = DRIVE_BASE / 'test.zip'\n",
            "LOCAL_DATA = Path('/content/data')\n",
            "MODELS_DIR = DRIVE_BASE / 'models'\n",
            "RESULTS_DIR = DRIVE_BASE / 'results' / 'unet'\n",
            "\n",
            "MODELS_DIR.mkdir(parents=True, exist_ok=True)\n",
            "RESULTS_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "print('Notebook VERSION:', VERSION)\n",
            "print('Drive base :', DRIVE_BASE)\n",
            "print('Data zip   :', DATA_ZIP, '→', DATA_ZIP.exists())\n",
            "print('Test zip   :', TEST_ZIP, '→', TEST_ZIP.exists())\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.tif', '.tiff'}\n",
            "\n",
            "\n",
            "def _count_images(folder: Path) -> int:\n",
            "    if not folder.exists():\n",
            "        return 0\n",
            "    return sum(1 for f in folder.iterdir() if f.suffix.lower() in IMAGE_EXTS)\n",
            "\n",
            "\n",
            "def _first_existing(*candidates: Path) -> Path | None:\n",
            "    for p in candidates:\n",
            "        if p is not None and p.exists() and _count_images(p) > 0:\n",
            "            return p\n",
            "    return None\n",
            "\n",
            "\n",
            "def prepare_local_data(force: bool = False) -> tuple[Path, Path]:\n",
            "    \"\"\"Unzip data.zip to /content/data and normalize to train/images + train/masks.\"\"\"\n",
            "    train_img = LOCAL_DATA / 'train' / 'images'\n",
            "    train_msk = LOCAL_DATA / 'train' / 'masks'\n",
            "    if not force and train_img.exists() and _count_images(train_img) > 0:\n",
            "        print('Using cached local data:', train_img)\n",
            "        return train_img, train_msk\n",
            "\n",
            "    if not DATA_ZIP.exists():\n",
            "        raise FileNotFoundError(f'Upload data.zip to {DATA_ZIP}')\n",
            "\n",
            "    tmp = LOCAL_DATA / '_zip_extract'\n",
            "    if tmp.exists():\n",
            "        shutil.rmtree(tmp)\n",
            "    tmp.mkdir(parents=True)\n",
            "\n",
            "    print('Extracting', DATA_ZIP)\n",
            "    with zipfile.ZipFile(DATA_ZIP, 'r') as zf:\n",
            "        zf.extractall(tmp)\n",
            "\n",
            "    flat_img = tmp / 'images'\n",
            "    flat_msk = tmp / 'masks'\n",
            "    if flat_img.exists() and flat_msk.exists():\n",
            "        train_img.parent.mkdir(parents=True, exist_ok=True)\n",
            "        shutil.rmtree(LOCAL_DATA / 'train', ignore_errors=True)\n",
            "        shutil.copytree(flat_img, train_img)\n",
            "        shutil.copytree(flat_msk, train_msk)\n",
            "    elif (tmp / 'train' / 'images').exists():\n",
            "        shutil.rmtree(LOCAL_DATA, ignore_errors=True)\n",
            "        shutil.copytree(tmp, LOCAL_DATA)\n",
            "    else:\n",
            "        raise FileNotFoundError('Expected images/ + masks/ or train/images inside data.zip')\n",
            "\n",
            "    shutil.rmtree(tmp, ignore_errors=True)\n",
            "    print('Train images:', _count_images(train_img))\n",
            "    return train_img, train_msk\n",
            "\n",
            "\n",
            "def prepare_test_data() -> tuple[Path | None, Path | None]:\n",
            "    \"\"\"Copy independent test images/masks from Drive if present.\"\"\"\n",
            "    test_img = LOCAL_DATA / 'test' / 'images'\n",
            "    test_msk = LOCAL_DATA / 'test' / 'masks'\n",
            "    if _count_images(test_img) > 0:\n",
            "        print('Using cached test data:', test_img, '| masks:', _count_images(test_msk))\n",
            "        return test_img, test_msk if _count_images(test_msk) > 0 else None\n",
            "\n",
            "    drive_img = _first_existing(\n",
            "        DRIVE_BASE / 'test_images' / 'final_images',\n",
            "        DRIVE_BASE / 'test' / 'images',\n",
            "        DRIVE_BASE / 'test_images' / 'images',\n",
            "    )\n",
            "    drive_msk = _first_existing(\n",
            "        DRIVE_BASE / 'test_images' / 'final_masks',\n",
            "        DRIVE_BASE / 'test' / 'masks',\n",
            "        DRIVE_BASE / 'test_images' / 'masks',\n",
            "    )\n",
            "\n",
            "    if drive_img is None and TEST_ZIP.exists():\n",
            "        tmp = Path('/content/_test_extract')\n",
            "        if tmp.exists():\n",
            "            shutil.rmtree(tmp)\n",
            "        tmp.mkdir()\n",
            "        print('Extracting', TEST_ZIP)\n",
            "        with zipfile.ZipFile(TEST_ZIP, 'r') as zf:\n",
            "            zf.extractall(tmp)\n",
            "        drive_img = _first_existing(\n",
            "            tmp / 'final_images', tmp / 'images', tmp / 'test' / 'images',\n",
            "            tmp / 'test_images' / 'final_images',\n",
            "        )\n",
            "        drive_msk = _first_existing(\n",
            "            tmp / 'final_masks', tmp / 'masks', tmp / 'test' / 'masks',\n",
            "            tmp / 'test_images' / 'final_masks',\n",
            "        )\n",
            "        if drive_img is not None:\n",
            "            shutil.copytree(drive_img, test_img)\n",
            "            if drive_msk is not None:\n",
            "                shutil.copytree(drive_msk, test_msk)\n",
            "        shutil.rmtree(tmp, ignore_errors=True)\n",
            "    elif drive_img is not None:\n",
            "        shutil.copytree(drive_img, test_img)\n",
            "        if drive_msk is not None:\n",
            "            shutil.copytree(drive_msk, test_msk)\n",
            "\n",
            "    if _count_images(test_img) == 0:\n",
            "        print('No independent test set found. Quantitative table will use the validation split.')\n",
            "        return None, None\n",
            "    print('Test images:', _count_images(test_img), '| Test masks:', _count_images(test_msk))\n",
            "    return test_img, test_msk if _count_images(test_msk) > 0 else None\n",
            "\n",
            "\n",
            "images_dir, masks_dir = prepare_local_data(force=False)\n",
            "test_images_dir, test_masks_dir = prepare_test_data()\n",
            "print('Train images:', images_dir)\n",
            "print('Train masks :', masks_dir)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import cv2\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import tqdm\n",
            "import tensorflow as tf\n",
            "from matplotlib import pyplot as plt\n",
            "from sklearn.model_selection import train_test_split\n",
            "from tensorflow.keras import Model, Input\n",
            "from tensorflow.keras.applications import MobileNetV2\n",
            "from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess\n",
            "from tensorflow.keras.layers import (\n",
            "    BatchNormalization, Concatenate, Conv2D, Conv2DTranspose, Dropout,\n",
            "    GlobalAveragePooling2D, ReLU, Resizing,\n",
            ")\n",
            "from tensorflow.keras.metrics import MeanIoU\n",
            "\n",
            "tf.keras.mixed_precision.set_global_policy('mixed_float16')\n",
            "\n",
            "OUTPUT_CHANNELS = 4\n",
            "SIZE_X = 512\n",
            "SIZE_Y = 512\n",
            "CLASS_NAMES = ('Roof', 'Window', 'Wall', 'Other')\n",
            "TABLE_NAMES = ('Windows', 'Walls', 'Roofs', 'Other')\n",
            "TABLE_INDICES = (1, 2, 0, 3)  # Window, Wall, Roof, Other\n",
            "CLASS_WEIGHTS_NP = np.array([1.0, 3.5, 2.5, 0.5], dtype=np.float32)  # Roof, Window, Wall, Other\n",
            "FOCAL_ALPHA = (0.15, 0.40, 0.35, 0.10)\n",
            "DROPOUT_RATE = 0.30\n",
            "L2_WEIGHT = 1e-4\n",
            "FINE_TUNE_AT = 100\n",
            "\n",
            "CLASS_LUT = np.full(256, 3, dtype=np.int32)  # unknown → Other\n",
            "CLASS_LUT[72] = 0\n",
            "CLASS_LUT[128] = 1\n",
            "CLASS_LUT[220] = 2\n",
            "CLASS_LUT[255] = 3\n",
            "\n",
            "\n",
            "def pair_image_mask_paths(img_dir: Path, mask_dir: Path) -> list[tuple[str, str]]:\n",
            "    pairs = []\n",
            "    for img_path in sorted(img_dir.iterdir()):\n",
            "        if img_path.suffix.lower() not in {'.png', '.jpg', '.jpeg'}:\n",
            "            continue\n",
            "        stem = img_path.stem\n",
            "        mask_stem = stem.replace('_texture', '_mask') if stem.endswith('_texture') else f'{stem}_mask'\n",
            "        mask_path = None\n",
            "        for ext in (img_path.suffix, '.png', '.jpg', '.jpeg'):\n",
            "            candidate = mask_dir / f'{mask_stem}{ext}'\n",
            "            if candidate.exists():\n",
            "                mask_path = candidate\n",
            "                break\n",
            "            same_name = mask_dir / f'{stem}{ext}'\n",
            "            if same_name.exists():\n",
            "                mask_path = same_name\n",
            "                break\n",
            "        if mask_path is None:\n",
            "            raise FileNotFoundError(f'No mask for {img_path.name}')\n",
            "        pairs.append((str(img_path), str(mask_path)))\n",
            "    return pairs\n",
            "\n",
            "\n",
            "def load_rgb(path: str) -> np.ndarray:\n",
            "    bgr = cv2.imread(path, cv2.IMREAD_COLOR)\n",
            "    if bgr is None:\n",
            "        raise FileNotFoundError(path)\n",
            "    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\n",
            "    rgb = cv2.resize(rgb, (SIZE_X, SIZE_Y), interpolation=cv2.INTER_LINEAR)\n",
            "    return rgb.astype(np.float32) / 255.0\n",
            "\n",
            "\n",
            "def load_mask(path: str) -> np.ndarray:\n",
            "    mask = cv2.imread(path, cv2.IMREAD_GRAYSCALE)\n",
            "    if mask is None:\n",
            "        raise FileNotFoundError(path)\n",
            "    mask = cv2.resize(mask, (SIZE_X, SIZE_Y), interpolation=cv2.INTER_NEAREST)\n",
            "    return CLASS_LUT[mask].astype(np.int32)\n",
            "\n",
            "\n",
            "pairs = pair_image_mask_paths(images_dir, masks_dir)\n",
            "print(f'Paired train samples: {len(pairs)}')\n",
            "print('First pair:', pairs[0])\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "train_images, train_masks = [], []\n",
            "\n",
            "for img_path, mask_path in tqdm.tqdm(pairs, desc='Loading RGB + masks'):\n",
            "    train_images.append(load_rgb(img_path))\n",
            "    train_masks.append(load_mask(mask_path))\n",
            "\n",
            "train_images = np.array(train_images, dtype=np.float32)\n",
            "train_masks = np.array(train_masks, dtype=np.int32)\n",
            "\n",
            "X_train, X_val, y_train, y_val = train_test_split(\n",
            "    train_images, train_masks, test_size=0.10, random_state=42, shuffle=True\n",
            ")\n",
            "print('Train:', len(X_train), '| Val:', len(X_val))\n",
            "print('Classes:', np.unique(y_train))\n",
            "for i, name in enumerate(CLASS_NAMES):\n",
            "    frac = np.mean(y_train == i)\n",
            "    print(f'  {name:8s}: {frac:.3f} of train pixels')\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def augment(image, mask):\n",
            "    mask = tf.cast(mask, tf.int32)\n",
            "    if tf.random.uniform(()) > 0.5:\n",
            "        return image, mask\n",
            "    if tf.random.uniform(()) > 0.5:\n",
            "        image = tf.image.flip_left_right(image)\n",
            "        mask = tf.image.flip_left_right(tf.expand_dims(mask, -1))[..., 0]\n",
            "    image = tf.image.random_brightness(image, max_delta=0.15)\n",
            "    image = tf.image.random_contrast(image, 0.85, 1.15)\n",
            "    image = tf.image.random_saturation(image, 0.85, 1.15)\n",
            "    noise = tf.random.normal(tf.shape(image), stddev=0.02, dtype=image.dtype)\n",
            "    image = tf.clip_by_value(image + noise, 0.0, 1.0)\n",
            "    return image, mask\n",
            "\n",
            "\n",
            "def apply_backbone_preprocess(image, mask):\n",
            "    image = mobilenet_preprocess(image * 255.0)\n",
            "    return image, mask\n",
            "\n",
            "\n",
            "def build_dataset(X, Y, training=True, batch_size=8):\n",
            "    ds = tf.data.Dataset.from_tensor_slices((X, Y))\n",
            "    if training:\n",
            "        ds = ds.shuffle(len(X)).map(augment, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    ds = ds.map(apply_backbone_preprocess, num_parallel_calls=tf.data.AUTOTUNE)\n",
            "    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "CLASS_WEIGHTS = tf.constant(CLASS_WEIGHTS_NP, dtype=tf.float32)\n",
            "\n",
            "\n",
            "def conv_block(x, filters, dropout_rate=DROPOUT_RATE, l2=L2_WEIGHT):\n",
            "    for _ in range(2):\n",
            "        x = Conv2D(\n",
            "            filters, 3, padding='same', use_bias=False,\n",
            "            kernel_regularizer=tf.keras.regularizers.l2(l2),\n",
            "        )(x)\n",
            "        x = BatchNormalization()(x)\n",
            "        x = ReLU()(x)\n",
            "    return Dropout(dropout_rate)(x)\n",
            "\n",
            "\n",
            "def upsample_block(filters, size=3):\n",
            "    return tf.keras.Sequential([\n",
            "        Conv2DTranspose(filters, size, strides=2, padding='same', use_bias=False),\n",
            "        BatchNormalization(),\n",
            "        ReLU(),\n",
            "    ])\n",
            "\n",
            "\n",
            "def aspp_block(x, filters=256, rates=(6, 12)):\n",
            "    branches = []\n",
            "    b = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "               kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "    b = BatchNormalization()(b)\n",
            "    branches.append(ReLU()(b))\n",
            "    for rate in rates:\n",
            "        b = Conv2D(filters, 3, padding='same', dilation_rate=rate, use_bias=False,\n",
            "                   kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "        b = BatchNormalization()(b)\n",
            "        branches.append(ReLU()(b))\n",
            "    gap = GlobalAveragePooling2D(keepdims=True)(x)\n",
            "    gap = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "                 kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(gap)\n",
            "    gap = BatchNormalization()(gap)\n",
            "    gap = ReLU()(gap)\n",
            "    gap = Resizing(int(x.shape[1]), int(x.shape[2]), interpolation='bilinear')(gap)\n",
            "    branches.append(gap)\n",
            "    x = Concatenate()(branches)\n",
            "    x = Conv2D(filters, 1, padding='same', use_bias=False,\n",
            "               kernel_regularizer=tf.keras.regularizers.l2(L2_WEIGHT))(x)\n",
            "    x = BatchNormalization()(x)\n",
            "    return ReLU()(x)\n",
            "\n",
            "\n",
            "def weighted_dice_loss(y_true, y_pred, smooth=1e-6):\n",
            "    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS)\n",
            "    y_pred = tf.cast(y_pred, tf.float32)\n",
            "    intersection = tf.reduce_sum(y_true_oh * y_pred, axis=[0, 1, 2])\n",
            "    denom = tf.reduce_sum(y_true_oh, axis=[0, 1, 2]) + tf.reduce_sum(y_pred, axis=[0, 1, 2])\n",
            "    dice = (2.0 * intersection + smooth) / (denom + smooth)\n",
            "    return 1.0 - tf.reduce_sum(dice * CLASS_WEIGHTS) / tf.reduce_sum(CLASS_WEIGHTS)\n",
            "\n",
            "\n",
            "def focal_loss(y_true, y_pred, gamma=2.0):\n",
            "    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS)\n",
            "    y_pred = tf.clip_by_value(tf.cast(y_pred, tf.float32), 1e-7, 1.0 - 1e-7)\n",
            "    ce = -y_true_oh * tf.math.log(y_pred)\n",
            "    alpha = tf.reshape(tf.constant(FOCAL_ALPHA, dtype=tf.float32), (1, 1, 1, -1))\n",
            "    weight = alpha * y_true_oh * tf.pow(1.0 - y_pred, gamma)\n",
            "    return tf.reduce_mean(tf.reduce_sum(weight * ce, axis=-1))\n",
            "\n",
            "\n",
            "def boundary_loss(y_true, y_pred):\n",
            "    y_true_oh = tf.cast(tf.one_hot(tf.cast(y_true, tf.int32), OUTPUT_CHANNELS), tf.float32)\n",
            "    y_pred = tf.cast(y_pred, tf.float32)\n",
            "    sobel = tf.image.sobel_edges(y_true_oh)\n",
            "    edges = tf.sqrt(tf.reduce_sum(tf.square(sobel), axis=-1) + 1e-6)\n",
            "    edges = tf.clip_by_value(edges, 0.0, 1.0)\n",
            "    ce = -y_true_oh * tf.math.log(tf.clip_by_value(y_pred, 1e-7, 1.0))\n",
            "    return tf.reduce_mean(tf.reduce_sum(ce * (1.0 + 3.0 * edges), axis=-1))\n",
            "\n",
            "\n",
            "def combined_loss(y_true, y_pred):\n",
            "    return (\n",
            "        0.50 * weighted_dice_loss(y_true, y_pred)\n",
            "        + 0.35 * focal_loss(y_true, y_pred)\n",
            "        + 0.15 * boundary_loss(y_true, y_pred)\n",
            "    )\n",
            "\n",
            "\n",
            "class MeanIoUFromLogits(MeanIoU):\n",
            "    \"\"\"MeanIoU for softmax output — argmax predictions before update.\"\"\"\n",
            "\n",
            "    def update_state(self, y_true, y_pred, sample_weight=None):\n",
            "        y_true = tf.cast(y_true, tf.int32)\n",
            "        y_pred = tf.cast(tf.argmax(y_pred, axis=-1), tf.int32)\n",
            "        return super().update_state(y_true, y_pred, sample_weight)\n",
            "\n",
            "\n",
            "def unet_model(output_channels=4, dropout_rate=DROPOUT_RATE):\n",
            "    h, w, c = SIZE_Y, SIZE_X, 3\n",
            "    base = MobileNetV2(input_shape=[h, w, c], include_top=False, weights='imagenet')\n",
            "    layer_names = [\n",
            "        'block_1_expand_relu', 'block_3_expand_relu', 'block_6_expand_relu',\n",
            "        'block_13_expand_relu', 'block_16_project',\n",
            "    ]\n",
            "    down_stack = Model(base.input, [base.get_layer(n).output for n in layer_names], name='mobilenetv2_encoder')\n",
            "    down_stack.trainable = False\n",
            "\n",
            "    decoder_filters = (256, 128, 64, 32)\n",
            "    up_stack = [upsample_block(f) for f in decoder_filters]\n",
            "\n",
            "    inputs = Input(shape=[h, w, c], name='input_image')\n",
            "    skips = down_stack(inputs)\n",
            "    x = aspp_block(skips[-1], filters=256)\n",
            "    for up, skip, filt in zip(up_stack, reversed(skips[:-1]), decoder_filters):\n",
            "        skip = Conv2D(filt, 1, padding='same', use_bias=False)(skip)\n",
            "        skip = BatchNormalization()(skip)\n",
            "        skip = ReLU()(skip)\n",
            "        x = up(x)\n",
            "        x = Concatenate()([x, skip])\n",
            "        x = conv_block(x, filt, dropout_rate)\n",
            "    x = Conv2DTranspose(output_channels, 3, strides=2, padding='same', dtype='float32')(x)\n",
            "    outputs = tf.keras.layers.Activation('softmax', dtype='float32', name='mask')(x)\n",
            "    return Model(inputs, outputs, name='unet_mobilenetv2'), down_stack\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def create_mask(pred_mask):\n",
            "    return tf.argmax(pred_mask, axis=-1)[0].numpy()\n",
            "\n",
            "\n",
            "def show_predictions(epoch, sample_idx=None, tag='train'):\n",
            "    if sample_idx is None:\n",
            "        sample_idx = min(50, max(len(X_val) - 1, 0))\n",
            "    x = X_val[sample_idx:sample_idx + 1]\n",
            "    x_in = mobilenet_preprocess(x * 255.0)\n",
            "    pred = create_mask(model.predict(x_in, verbose=0))\n",
            "    fig = plt.figure(figsize=(12, 4))\n",
            "    for col, (title, arr) in enumerate([\n",
            "        ('Input', np.clip(X_val[sample_idx], 0, 1)),\n",
            "        ('Ground Truth', y_val[sample_idx]),\n",
            "        ('Prediction', pred),\n",
            "    ]):\n",
            "        ax = fig.add_subplot(1, 3, col + 1)\n",
            "        ax.imshow(arr if col == 0 else arr, cmap=None if col == 0 else 'jet', vmin=0, vmax=3 if col else None)\n",
            "        ax.set_title(title)\n",
            "        ax.axis('off')\n",
            "    fig.suptitle(f'{tag} · epoch {epoch + 1}')\n",
            "    out = RESULTS_DIR / f'{tag}_epoch_{epoch + 1:03d}.png'\n",
            "    fig.savefig(out, dpi=100, bbox_inches='tight')\n",
            "    plt.show()\n",
            "    plt.close(fig)\n",
            "\n",
            "\n",
            "class DisplayCallback(tf.keras.callbacks.Callback):\n",
            "    def __init__(self, every_n=5, tag='stage'):\n",
            "        super().__init__()\n",
            "        self.every_n = every_n\n",
            "        self.tag = tag\n",
            "\n",
            "    def on_epoch_end(self, epoch, logs=None):\n",
            "        if (epoch + 1) % self.every_n == 0 or epoch == 0:\n",
            "            show_predictions(epoch, tag=self.tag)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def compile_model(lr):\n",
            "    model.compile(\n",
            "        optimizer=tf.keras.optimizers.AdamW(\n",
            "            learning_rate=lr, weight_decay=1e-5, clipnorm=1.0,\n",
            "        ),\n",
            "        loss=combined_loss,\n",
            "        metrics=[\n",
            "            tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy'),\n",
            "            MeanIoUFromLogits(num_classes=OUTPUT_CHANNELS, name='mean_iou'),\n",
            "        ],\n",
            "    )\n",
            "\n",
            "\n",
            "model, down_stack = unet_model(OUTPUT_CHANNELS, dropout_rate=DROPOUT_RATE)\n",
            "compile_model(1e-3)\n",
            "model.summary()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "BATCH_SIZE = 8\n",
            "STAGE1_EPOCHS = 20\n",
            "STAGE2_EPOCHS = 80\n",
            "checkpoint_path = MODELS_DIR / 'unet_mobilenetv2.keras'\n",
            "\n",
            "train_ds = build_dataset(X_train, y_train, training=True, batch_size=BATCH_SIZE)\n",
            "val_ds = build_dataset(X_val, y_val, training=False, batch_size=BATCH_SIZE)\n",
            "steps_per_epoch = int(np.ceil(len(X_train) / BATCH_SIZE))\n",
            "\n",
            "def make_callbacks(tag, patience):\n",
            "    cbs = [\n",
            "        DisplayCallback(every_n=5, tag=tag),\n",
            "        tf.keras.callbacks.ModelCheckpoint(\n",
            "            str(checkpoint_path), monitor='val_mean_iou', mode='max',\n",
            "            save_best_only=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.EarlyStopping(\n",
            "            monitor='val_mean_iou', mode='max', patience=patience,\n",
            "            restore_best_weights=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.ReduceLROnPlateau(\n",
            "            monitor='val_mean_iou', mode='max', factor=0.5, patience=5,\n",
            "            min_lr=1e-7, verbose=1,\n",
            "        ),\n",
            "    ]\n",
            "    return cbs\n",
            "\n",
            "print('Stage 1: frozen MobileNetV2 encoder, train decoder')\n",
            "history1 = model.fit(\n",
            "    train_ds, validation_data=val_ds, epochs=STAGE1_EPOCHS,\n",
            "    callbacks=make_callbacks('stage1', patience=8),\n",
            ")\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "print('Stage 2: fine-tune encoder from layer', FINE_TUNE_AT, '(BatchNorm stays frozen)')\n",
            "if checkpoint_path.exists():\n",
            "    model.load_weights(str(checkpoint_path))\n",
            "    print('Loaded best Stage-1 weights')\n",
            "down_stack.trainable = True\n",
            "for i, layer in enumerate(down_stack.layers):\n",
            "    if isinstance(layer, BatchNormalization):\n",
            "        layer.trainable = False\n",
            "    else:\n",
            "        layer.trainable = i >= FINE_TUNE_AT\n",
            "\n",
            "cosine = tf.keras.optimizers.schedules.CosineDecay(\n",
            "    initial_learning_rate=3e-5,\n",
            "    decay_steps=max(steps_per_epoch * STAGE2_EPOCHS, 1),\n",
            "    alpha=0.01,\n",
            ")\n",
            "model.compile(\n",
            "    optimizer=tf.keras.optimizers.AdamW(\n",
            "        learning_rate=cosine, weight_decay=1e-5, clipnorm=1.0,\n",
            "    ),\n",
            "    loss=combined_loss,\n",
            "    metrics=[\n",
            "        tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy'),\n",
            "        MeanIoUFromLogits(num_classes=OUTPUT_CHANNELS, name='mean_iou'),\n",
            "    ],\n",
            ")\n",
            "\n",
            "history2 = model.fit(\n",
            "    train_ds, validation_data=val_ds, epochs=STAGE2_EPOCHS,\n",
            "    callbacks=[\n",
            "        DisplayCallback(every_n=5, tag='stage2'),\n",
            "        tf.keras.callbacks.ModelCheckpoint(\n",
            "            str(checkpoint_path), monitor='val_mean_iou', mode='max',\n",
            "            save_best_only=True, verbose=1,\n",
            "        ),\n",
            "        tf.keras.callbacks.EarlyStopping(\n",
            "            monitor='val_mean_iou', mode='max', patience=15,\n",
            "            restore_best_weights=True, verbose=1,\n",
            "        ),\n",
            "    ],\n",
            ")\n",
            "print('Best model →', checkpoint_path)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def merge_history(*histories):\n",
            "    merged = {}\n",
            "    for h in histories:\n",
            "        for k, v in h.history.items():\n",
            "            merged.setdefault(k, []).extend(v)\n",
            "    return merged\n",
            "\n",
            "\n",
            "hist = merge_history(history1, history2)\n",
            "iou_key = 'mean_iou' if 'mean_iou' in hist else 'mean_io_u'\n",
            "plt.figure(figsize=(7, 4))\n",
            "plt.plot(hist[iou_key], label='train IoU')\n",
            "plt.plot(hist['val_' + iou_key], label='val IoU')\n",
            "plt.axvline(len(history1.history[iou_key]) - 0.5, color='gray', ls='--', lw=1, label='fine-tune start')\n",
            "plt.xlabel('Epoch')\n",
            "plt.ylabel('Mean IoU')\n",
            "plt.legend()\n",
            "plt.tight_layout()\n",
            "plt.savefig(RESULTS_DIR / 'training_curve.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Test-set class-wise metrics\n",
            "\n",
            "Pixel-wise Precision, Recall, F1-score, and IoU on the **independent test set** (falls back to the 10% validation split if test masks are missing). Never used during training when a true test split is present.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def load_split(img_dir: Path, msk_dir: Path):\n",
            "    split_pairs = pair_image_mask_paths(img_dir, msk_dir)\n",
            "    xs, ys = [], []\n",
            "    for ip, mp in tqdm.tqdm(split_pairs, desc=f'Loading {img_dir.name}'):\n",
            "        xs.append(load_rgb(ip))\n",
            "        ys.append(load_mask(mp))\n",
            "    return np.array(xs, dtype=np.float32), np.array(ys, dtype=np.int32), split_pairs\n",
            "\n",
            "\n",
            "def predict_masks(images: np.ndarray, batch_size=8) -> np.ndarray:\n",
            "    preds = []\n",
            "    for i in range(0, len(images), batch_size):\n",
            "        batch = mobilenet_preprocess(images[i:i + batch_size] * 255.0)\n",
            "        probs = model.predict(batch, verbose=0)\n",
            "        preds.append(np.argmax(probs, axis=-1).astype(np.int32))\n",
            "    return np.concatenate(preds, axis=0)\n",
            "\n",
            "\n",
            "def confusion_matrix(y_true: np.ndarray, y_pred: np.ndarray, num_classes=4) -> np.ndarray:\n",
            "    t = y_true.ravel().astype(np.int32)\n",
            "    p = y_pred.ravel().astype(np.int32)\n",
            "    valid = (t >= 0) & (t < num_classes) & (p >= 0) & (p < num_classes)\n",
            "    return np.bincount(t[valid] * num_classes + p[valid], minlength=num_classes * num_classes).reshape(num_classes, num_classes)\n",
            "\n",
            "\n",
            "def classwise_table(cm: np.ndarray) -> pd.DataFrame:\n",
            "    rows = []\n",
            "    for display_name, idx in zip(TABLE_NAMES, TABLE_INDICES):\n",
            "        tp = cm[idx, idx]\n",
            "        fp = cm[:, idx].sum() - tp\n",
            "        fn = cm[idx, :].sum() - tp\n",
            "        precision = tp / (tp + fp + 1e-6)\n",
            "        recall = tp / (tp + fn + 1e-6)\n",
            "        f1 = 2 * precision * recall / (precision + recall + 1e-6)\n",
            "        iou = tp / (tp + fp + fn + 1e-6)\n",
            "        rows.append({\n",
            "            'Class': display_name,\n",
            "            'Precision': float(precision),\n",
            "            'Recall': float(recall),\n",
            "            'F1-score': float(f1),\n",
            "            'IoU': float(iou),\n",
            "        })\n",
            "    df = pd.DataFrame(rows)\n",
            "    mean = df[['Precision', 'Recall', 'F1-score', 'IoU']].mean()\n",
            "    df.loc[len(df)] = ['Mean', mean['Precision'], mean['Recall'], mean['F1-score'], mean['IoU']]\n",
            "    return df\n",
            "\n",
            "\n",
            "eval_split = 'test'\n",
            "if test_images_dir is not None and test_masks_dir is not None:\n",
            "    X_eval, y_eval, eval_pairs = load_split(test_images_dir, test_masks_dir)\n",
            "    print(f'Independent test set: {len(X_eval)} images')\n",
            "else:\n",
            "    eval_split = 'validation'\n",
            "    X_eval, y_eval = X_val, y_val\n",
            "    print('WARNING: no test masks found — Table uses the held-out validation split, not an independent test set.')\n",
            "\n",
            "y_hat = predict_masks(X_eval)\n",
            "cm = confusion_matrix(y_eval, y_hat)\n",
            "metrics_df = classwise_table(cm)\n",
            "metrics_df_fmt = metrics_df.copy()\n",
            "for col in ('Precision', 'Recall', 'F1-score', 'IoU'):\n",
            "    metrics_df_fmt[col] = metrics_df_fmt[col].map(lambda v: f'{v:.4f}')\n",
            "\n",
            "def dataframe_to_markdown(df: pd.DataFrame) -> str:\n",
            "    cols = list(df.columns)\n",
            "    lines = ['| ' + ' | '.join(cols) + ' |', '| ' + ' | '.join(['---'] * len(cols)) + ' |']\n",
            "    for row in df.itertuples(index=False):\n",
            "        lines.append('| ' + ' | '.join(str(v) for v in row) + ' |')\n",
            "    return '\\n'.join(lines)\n",
            "\n",
            "\n",
            "print()\n",
            "print(f'Table. Class-wise quantitative performance of the semantic segmentation model on the {eval_split} dataset.')\n",
            "print()\n",
            "print(metrics_df_fmt.to_string(index=False))\n",
            "print()\n",
            "print(dataframe_to_markdown(metrics_df_fmt))\n",
            "\n",
            "csv_path = RESULTS_DIR / f'classwise_metrics_{eval_split}.csv'\n",
            "md_path = RESULTS_DIR / f'classwise_metrics_{eval_split}.md'\n",
            "metrics_df.to_csv(csv_path, index=False, float_format='%.6f')\n",
            "md_path.write_text(\n",
            "    f'Table. Class-wise quantitative performance of the semantic segmentation model on the {eval_split} dataset.\\n\\n'\n",
            "    + dataframe_to_markdown(metrics_df_fmt)\n",
            "    + '\\n',\n",
            "    encoding='utf-8',\n",
            ")\n",
            "print('Saved', csv_path)\n",
            "print('Saved', md_path)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "fig, ax = plt.subplots(figsize=(8.5, 2.8))\n",
            "ax.axis('off')\n",
            "ax.set_title(\n",
            "    f'Table. Class-wise quantitative performance on the {eval_split} dataset',\n",
            "    fontsize=11, pad=8,\n",
            ")\n",
            "cell_text = [metrics_df_fmt.iloc[i].tolist() for i in range(len(metrics_df_fmt))]\n",
            "table = ax.table(\n",
            "    cellText=cell_text,\n",
            "    colLabels=list(metrics_df_fmt.columns),\n",
            "    loc='center',\n",
            "    cellLoc='center',\n",
            ")\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(10)\n",
            "table.scale(1.15, 1.45)\n",
            "for (r, c), cell in table.get_celld().items():\n",
            "    if r == 0:\n",
            "        cell.set_facecolor('#d9e2ef')\n",
            "        cell.set_text_props(weight='bold')\n",
            "    elif r == len(cell_text):\n",
            "        cell.set_facecolor('#eef2f7')\n",
            "        cell.set_text_props(weight='bold')\n",
            "plt.tight_layout()\n",
            "fig.savefig(RESULTS_DIR / f'classwise_table_{eval_split}.png', dpi=160, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(5, 4))\n",
            "im = ax.imshow(cm, cmap='Blues')\n",
            "ax.set_xticks(range(4), CLASS_NAMES, rotation=30, ha='right')\n",
            "ax.set_yticks(range(4), CLASS_NAMES)\n",
            "ax.set_xlabel('Predicted')\n",
            "ax.set_ylabel('Ground truth')\n",
            "for i in range(4):\n",
            "    for j in range(4):\n",
            "        ax.text(j, i, f'{cm[i, j]:,}', ha='center', va='center', fontsize=8)\n",
            "fig.colorbar(im, ax=ax, fraction=0.046)\n",
            "plt.tight_layout()\n",
            "fig.savefig(RESULTS_DIR / f'confusion_matrix_{eval_split}.png', dpi=140, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "n_show = min(3, len(X_eval))\n",
            "fig, axes = plt.subplots(n_show, 3, figsize=(12, 3.5 * n_show))\n",
            "if n_show == 1:\n",
            "    axes = np.expand_dims(axes, 0)\n",
            "for i in range(n_show):\n",
            "    axes[i, 0].imshow(np.clip(X_eval[i], 0, 1))\n",
            "    axes[i, 0].set_title('Input')\n",
            "    axes[i, 1].imshow(y_eval[i], cmap='jet', vmin=0, vmax=3)\n",
            "    axes[i, 1].set_title('Ground truth')\n",
            "    axes[i, 2].imshow(y_hat[i], cmap='jet', vmin=0, vmax=3)\n",
            "    axes[i, 2].set_title('Prediction')\n",
            "    for ax in axes[i]:\n",
            "        ax.axis('off')\n",
            "plt.tight_layout()\n",
            "plt.savefig(RESULTS_DIR / f'{eval_split}_samples.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
]


def _as_source(text: str) -> list[str]:
    if not text.endswith("\n"):
        text += "\n"
    return [text]


# Normalize sources that were written as lists of lines already
for cell in cells:
    src = cell["source"]
    if isinstance(src, str):
        cell["source"] = _as_source(src)

OUT = ROOT / "U_NET_Segmentation.ipynb"
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
        "colab": {"provenance": [], "gpuType": "A100"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

OUT.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print(f"Wrote {OUT} ({len(cells)} cells)")
